### ISSUE TITLE
当一个新的节点加入集群时，原有集群中数据如何分配？

### ISSUE THREAD

**Issue by guang384** [codefollower/CCUG#12]
集群中现有数据在什么情况下会分流到新加入的阶段中？

还是只有在新数据插入的时候才会向新的节点中存储数据？

**Comment by guang384** [comment]
同样 如果节点撤出之后  那个在其上的备份数据会不会自动被备份到其他节点上？

**Comment by codefollower** [comment]
新节点上线，老节点退役，都涉及streaming还有无数其他模块，
连存储层的data文件的格式都考虑到如何更方便高效的传输数据了，
总的来说，这一块算是Cassandra中最复杂的一个功能实现了，
要讲清楚不是很容易，有时间时再写点文章吧。

**Comment by codefollower** [comment]
简单说就是: 
新节点启动时，先进入bootstrap阶段，会给它自动随机分配多个新的token(老的版本要手工生成)，
然后从整个ring中根据这些token生成一系列rang，这些rang是在原有节点上切出来的，
最后就让相关节点用streaming把包含rang的那些数据传过来，
bootstrap阶段完成后，新节点才进入正常状态。

节点退役后，会自动把它的数据传给其他节点。

**Comment by guang384** [comment]
收到，大致思路了解了。

期待您进一步的文章讲解。
