### ISSUE TITLE
关于broadcast_rpc_address

### ISSUE THREAD

**Issue by guang384** [codefollower/CCUG#13]
服务器内网和外网IP不同 
直接将broadcast_rpc_address配置为hostname但是日志依然是

15/11/10 16:59:32 INFO Cluster: New Cassandra host web1/42.**.*.**(外网IP):9042 added
15/11/10 16:59:32 INFO Cluster: New Cassandra host /192.168.1.100:9042 added

172.25.1.158 是内网地址 。。。

**Comment by codefollower** [comment]
它在加载cassandra.yaml时，调用了broadcastRpcAddress = InetAddress.getByName(config.broadcast_rpc_address);

然后打log时把broadcastRpcAddress字段打出来，
变成了broadcastRpcAddress.toString()就会把主机名和ip一起输出了，
比如，你把broadcast_rpc_address设成localhost，输出就是localhost/127.0.0.1。

你这个log是java-driver打的吧，Cassandra没有Cluster这个类。

**Comment by codefollower** [comment]
它里面的代码基本上都调用了InetAddress.getHostAddress()，所以显示的还是IP，
要想解决你的问题：隐藏IP，
目前想要做到，只有改代码了吧，把用到broadcastRpcAddress的地方改成InetAddress.getHostName()

**Comment by guang384** [comment]
是的  log是java-driver打得~

它这么设计的是如何考虑的？getHostAddress而不是getHostName

**Comment by codefollower** [comment]
你看一下java.net.InetAddress.getHostName()的JavaDoc就知道了，getHostName比getHostAddress慢

**Comment by codefollower** [comment]
java-driver的log把ip打出来有什么问题吗?  java-driver没有部署在内网？
这样的话9042端口也得通过防火墙配置才能允许访问啦？

**Comment by guang384** [comment]
目前我的场景：在开发过程中 想通过开发机去直接连接云服务器。这时的服务器就分内外网IP了。。

java-driver的log吧IP打印出来没有问题。
目前的场景java-driver确实和服务器不处于同一内网中。
9042端口已配置允许访问。。


以上是我目前的情况 （其实就是开发阶段 不想频繁部署，希望开发机可以直接变开发边验证逻辑）。将来上线肯定不会还是这个场景。

**Comment by codefollower** [comment]
这问题没有别的招了，代码写死了。

**Comment by guang384** [comment]
是啊，用所谓的敏捷开发那一套解决了。。svn commit 触发自动部署。。。 然后远程看结果。就是debug麻烦点得通过日志分析，不过已经很满意了 哈哈
