### ISSUE TITLE
rpc_address 和 broadcast_rpc_address这两个参数的作用和配置问题

### ISSUE THREAD

**Issue by guang384** [codefollower/CCUG#7]
您好，关于这两个参数有些疑问，文档的英文感觉描述的过于简略（或者是我没有get到精髓），Google也没有找到一个容易理解的回答。所以冒昧提问。

rpc_address 是客户端或者其他节点嗲用RPC协议绑定地址 。
那么broadcast_rpc_address 如何理解？
为何rpc_address 指定为公开访问（0.0.0.0）的时候broadcast_rpc_address 不能是这个呢？

**Comment by codefollower** [comment]
Client(通常指Cassandra的driver)可以通过两种方式来连Cassandra集群中的任何一个节点:
一种是Thrift，另一种是NativeTransport(也就是CQL的方式)
这两种方式都需要rpc_address来配置主机名，只是两者的端口不一样。

另外，Cassandra集群的节点之间也需要通信，
每个节点都会启动一个MessagingService监听线程来接收其他节点发来的信息，
MessagingService用的是listen_address这个参数。

如果rpc_address没有设置，默认就是用listen_address

broadcast_rpc_address并没有多大用处，
通常是在Cassandra集群的节点上下线后，给Client发送一些拓扑改变的信息，
这些信息里就有这个broadcast_rpc_address，
如果没指定broadcastRpcAddress，用的就是rpc_address。

除上面列的这些外，还有broadcast_address、listen_interface……
经常把人搞糊涂，乱糟糟的！

我一般只配个listen_address，
然后为Thrift、NativeTransport、MessagingService配不同端口就可以了，
Thrift不是必须的，如果不想支持Thrift了，在cassandra.yaml文件中加 start_rpc: false (现在默认就是false)


各种地址配置信息的验证在org.apache.cassandra.config.DatabaseDescriptor.applyAddressConfig(Config)。

**Comment by guang384** [comment]
分析的很细致 多谢~
