### ISSUE TITLE
CQL中数据类型 varchar和text的区别？

### ISSUE THREAD

**Issue by guang384** [codefollower/CCUG#9]
从文档描述上看。。这两没区别，那么使用的时候 这两有什么不同么？（还是底层实现一样？

下方是文档中关于 CQL Type 的描述：
> 《CQL for Cassandra 2.0 & 2.1 Documentation》（August 25, 2015） 中第57页

| CQL Type | Constants     | Description          |
| -------- |:-------------:| --------------------:|
| text     | strings       | UTF-8 encoded string |
| varchar  | strings       | UTF-8 encoded string |

**Comment by codefollower** [comment]
没差别，相当于同义词

**Comment by guang384** [comment]
好的 多谢确认！
